### ISSUE TITLE
Allow for dynamic scope definition via api

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/whisper#16]
The scopes Whisper can handle today are defined in build time. 

It would be interesting to have them defined in runtime, via API, so Whisper registered Clients can inform their own scopes.

**Comment by claudiosegala** [comment]
@abilioesteves just to check, these are the steps for this issue:

1. Create a database for scopes definitions with fields: ClientID, Description, Alias, Details, Scope;
2. Seed the current default scopes during the build
3. Improve the retrieval of scopes to retrieve from the database

PS: ClientID would be nullable so that null meant that this scope is for all.

**Comment by eabili0** [comment]
@claudiosegala, this issue is now part of a more broad Milestone. The applications will now be registered by the user through a Whisper dashboard.

The proposed `Scopes Table` will have a `n:1` relationship with an `Applications Table`.

For that reason, I'm sunsetting this issue. The efforts will now be redirected to issues #59 and #58 .

Thanks!
