### ISSUE TITLE
Create email confirmation flow

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/whisper#5]

**Comment by claudiosegala** [comment]
Just to confirm. For this issue I should use [gorm transactions](http://jinzhu.me/gorm/advanced.html#transactions) to cancel the insertion in case of errors while sending the email, right?

Since there is no try catch in golang, I am planning on doing something like this:
```go
tx := db.Begin()
defer func() {
    if r := recover(); r != nil {
        tx.Rollback()
    }
  }()

res, err := DbOperation(tx, args)
gohtypes.Panic(err)

err = OtherDbOperation(tx, args) 
gohtypes.Panic(err)
```Just to confirm. For this issue I should use [gorm transactions](http://jinzhu.me/gorm/advanced.html#transactions) to cancel the insertion in case of errors while sending the email, right?

Since there is no try catch in golang, I am planning on doing something like this:
```go
tx := db.Begin()
defer func() {
    if r := recover(); r != nil {
        tx.Rollback()
    }
  }()

res, err := DbOperation(tx, args)
gohtypes.Panic(err)

err = OtherDbOperation(tx, args) 
gohtypes.Panic(err)
```

**Comment by claudiosegala** [comment]
> `db, err := gorm.Open("mysql", dao.DatabaseURL)`

Is there a reason to open a connection with gorm every time?

**Comment by abilioesteves** [comment]
Nope. After a successful insertion, the email should be sent asynchronously (maybe use a special goroutine just to send the emails added to an email channel?). No instantaneous feedback needed for the user regarding the success or not of the email sending operation.

**Comment by abilioesteves** [comment]
There is already an open issue to change this frequent gorm.Open() behaviour.

**Comment by claudiosegala** [comment]
> Nope. After a successful insertion, the email should be sent asynchronously (maybe use a special goroutine just to send the emails added to an email channel?). No instantaneous feedback needed for the user regarding the success or not of the email sending operation.

I will be using a goroutine to send the emails then.

**Comment by claudiosegala** [comment]
> There is already an open issue to change this frequent gorm.Open() behaviour #8

Fair enough.
